apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes
spec:
  ports:
  - nodePort: 31282
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-kubernetes
  sessionAffinity: None
  type: NodePort
